# Advanced Forecasting Models

> **AUTHORITATIVE GENERATION — PROPHET + DEFERRED NEURALFORECAST SCOPE**  
> This executed notebook generates the validated Prophet 30-day periodic-refit vector and records the deferred PatchTST/iTransformer environment status. ARIMA, Simple Exponential Smoothing, and Holt-Winters rolling one-step results now live in `02_Classical_Models.ipynb` alongside their retained historical static-protocol results.

## 1. Protocol and Environment

Prophet uses a clearly labelled 30-day periodic-refit compromise with the latest 128 strictly prior observed prices at every refit. It is not described as rolling one-step. The classical statistical models were consolidated into Notebook 02 so their historical static and authoritative fair results cannot diverge across notebooks.

In [1]:
from pathlib import Path
import sys
import numpy as np
import pandas as pd

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()
sys.path.append(str(PROJECT_ROOT))

from src.bitcoin_advanced_models import (
    periodic_refit_prophet_forecast,
    validate_and_save_forecast,
)
from src.data_loader import load_bitcoin_data
from src.preprocessing import prepare_daily_bitcoin_data
from src.metrics import mae, rmse, mape, smape
pd.set_option('display.float_format', '{:.6f}'.format)

E:\Re_Sc_AM\TimeSeriesFoundationModels\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Importing plotly failed. Interactive plots will not work.

## 2. Load Dataset and Freeze Split

In [2]:
data_path = PROJECT_ROOT / 'data' / 'bitcoin' / 'btcusd_1-min_data.csv'
raw = load_bitcoin_data(data_path)
daily = prepare_daily_bitcoin_data(raw)
target = daily['Close'].asfreq('D').dropna()
split_index = int(len(target) * 0.8)
train = target.iloc[:split_index]
test = target.iloc[split_index:]
assert len(train) == 4241 and len(test) == 1061
assert train.index.max() < test.index.min()
pd.DataFrame({'Segment':['Train','Test'], 'Rows':[len(train),len(test)], 'Start':[train.index.min(),test.index.min()], 'End':[train.index.max(),test.index.max()]})

  Segment  Rows                     Start                       End
0   Train  4241 2012-01-01 00:00:00+00:00 2023-08-11 00:00:00+00:00
1    Test  1061 2023-08-12 00:00:00+00:00 2026-07-07 00:00:00+00:00

## 3. Prophet 30-Day Periodic Refit

Prophet is refitted every 30 days using the latest 128 observations available strictly before the refit date. Forecasts between refits use that fitted model without incorporating future observations.

In [3]:
prophet_forecast = periodic_refit_prophet_forecast(target, test.index, context_length=128, refit_every=30)
prophet_frame = validate_and_save_forecast(prophet_forecast, test.index, PROJECT_ROOT / 'results' / 'prophet_rolling_forecast.csv')
prophet_metrics = pd.DataFrame([{'Model':'Prophet 30-Day Periodic Refit','MAE':mae(test,prophet_forecast),'RMSE':rmse(test,prophet_forecast),'MAPE':mape(test,prophet_forecast),'sMAPE':smape(test,prophet_forecast)}]).set_index('Model')
prophet_metrics

09:56:57 - cmdstanpy - INFO - Chain [1] start processing

09:56:57 - cmdstanpy - INFO - Chain [1] done processing

09:56:58 - cmdstanpy - INFO - Chain [1] start processing

09:56:58 - cmdstanpy - INFO - Chain [1] done processing

09:56:58 - cmdstanpy - INFO - Chain [1] start processing

09:56:58 - cmdstanpy - INFO - Chain [1] done processing

09:56:59 - cmdstanpy - INFO - Chain [1] start processing

09:56:59 - cmdstanpy - INFO - Chain [1] done processing

09:56:59 - cmdstanpy - INFO - Chain [1] start processing

09:56:59 - cmdstanpy - INFO - Chain [1] done processing

09:57:00 - cmdstanpy - INFO - Chain [1] start processing

09:57:00 - cmdstanpy - INFO - Chain [1] done processing

09:57:01 - cmdstanpy - INFO - Chain [1] start processing

09:57:01 - cmdstanpy - INFO - Chain [1] done processing

09:57:01 - cmdstanpy - INFO - Chain [1] start processing

09:57:01 - cmdstanpy - INFO - Chain [1] done processing

09:57:02 - cmdstanpy - INFO - Chain [1] start processing

09:57:02 - cmdstanpy - INFO - Chain [1] done processing

09:57:02 - cmdstanpy - INFO - Chain [1] start processing

09:57:02 - cmdstanpy - INFO - Chain [1] done processing

09:57:03 - cmdstanpy - INFO - Chain [1] start processing

09:57:03 - cmdstanpy - INFO - Chain [1] done processing

09:57:03 - cmdstanpy - INFO - Chain [1] start processing

09:57:03 - cmdstanpy - INFO - Chain [1] done processing

09:57:04 - cmdstanpy - INFO - Chain [1] start processing

09:57:04 - cmdstanpy - INFO - Chain [1] done processing

09:57:04 - cmdstanpy - INFO - Chain [1] start processing

09:57:04 - cmdstanpy - INFO - Chain [1] done processing

09:57:05 - cmdstanpy - INFO - Chain [1] start processing

09:57:05 - cmdstanpy - INFO - Chain [1] done processing

09:57:05 - cmdstanpy - INFO - Chain [1] start processing

09:57:05 - cmdstanpy - INFO - Chain [1] done processing

09:57:06 - cmdstanpy - INFO - Chain [1] start processing

09:57:06 - cmdstanpy - INFO - Chain [1] done processing

09:57:06 - cmdstanpy - INFO - Chain [1] start processing

09:57:06 - cmdstanpy - INFO - Chain [1] done processing

09:57:07 - cmdstanpy - INFO - Chain [1] start processing

09:57:07 - cmdstanpy - INFO - Chain [1] done processing

09:57:07 - cmdstanpy - INFO - Chain [1] start processing

09:57:07 - cmdstanpy - INFO - Chain [1] done processing

09:57:08 - cmdstanpy - INFO - Chain [1] start processing

09:57:08 - cmdstanpy - INFO - Chain [1] done processing

09:57:08 - cmdstanpy - INFO - Chain [1] start processing

09:57:08 - cmdstanpy - INFO - Chain [1] done processing

09:57:09 - cmdstanpy - INFO - Chain [1] start processing

09:57:09 - cmdstanpy - INFO - Chain [1] done processing

09:57:09 - cmdstanpy - INFO - Chain [1] start processing

09:57:09 - cmdstanpy - INFO - Chain [1] done processing

09:57:10 - cmdstanpy - INFO - Chain [1] start processing

09:57:10 - cmdstanpy - INFO - Chain [1] done processing

09:57:10 - cmdstanpy - INFO - Chain [1] start processing

09:57:10 - cmdstanpy - INFO - Chain [1] done processing

09:57:11 - cmdstanpy - INFO - Chain [1] start processing

09:57:11 - cmdstanpy - INFO - Chain [1] done processing

09:57:11 - cmdstanpy - INFO - Chain [1] start processing

09:57:11 - cmdstanpy - INFO - Chain [1] done processing

09:57:12 - cmdstanpy - INFO - Chain [1] start processing

09:57:12 - cmdstanpy - INFO - Chain [1] done processing

09:57:12 - cmdstanpy - INFO - Chain [1] start processing

09:57:12 - cmdstanpy - INFO - Chain [1] done processing

09:57:13 - cmdstanpy - INFO - Chain [1] start processing

09:57:13 - cmdstanpy - INFO - Chain [1] done processing

09:57:13 - cmdstanpy - INFO - Chain [1] start processing

09:57:13 - cmdstanpy - INFO - Chain [1] done processing

09:57:14 - cmdstanpy - INFO - Chain [1] start processing

09:57:14 - cmdstanpy - INFO - Chain [1] done processing

09:57:15 - cmdstanpy - INFO - Chain [1] start processing

09:57:15 - cmdstanpy - INFO - Chain [1] done processing

09:57:15 - cmdstanpy - INFO - Chain [1] start processing

09:57:15 - cmdstanpy - INFO - Chain [1] done processing

09:57:16 - cmdstanpy - INFO - Chain [1] start processing

09:57:16 - cmdstanpy - INFO - Chain [1] done processing

                                      MAE         RMSE      MAPE     sMAPE
Model
Prophet 30-Day Periodic Refit 8195.262862 10781.162873 11.199767 11.287185

## 4. Deferred NeuralForecast Models

PatchTST and iTransformer via neuralforecast were not run in this environment. neuralforecast>=3.1.8 requires pytorch-lightning<2.6.0 (incompatible with the project's pinned lightning 2.6.5); neuralforecast==3.1.7 is compatible with lightning but imports ray[train,tune], which has no available Windows/Python 3.13 distribution in this environment as of this run. A separate Python 3.12 environment is recommended if these models are needed later.

## 5. Validate Prophet Against the Authoritative Comparison Artifact

The previously frozen classical vectors remain untouched. This check confirms the regenerated Prophet vector is aligned with the existing authoritative column without rewriting `validated_forecasts.csv`.

In [4]:
validated_path = PROJECT_ROOT / 'results' / 'validated_forecasts.csv'
validated = pd.read_csv(validated_path, parse_dates=['Timestamp'])
validated['Timestamp'] = pd.to_datetime(validated['Timestamp'], utc=True)
assert len(prophet_frame) == 1061
assert pd.DatetimeIndex(prophet_frame['Timestamp']).equals(test.index)
assert pd.DatetimeIndex(validated['Timestamp']).equals(pd.DatetimeIndex(prophet_frame['Timestamp']))
assert np.allclose(validated['Prophet_Periodic_Refit'], prophet_frame['Prophet_Periodic_Refit'], rtol=1e-12, atol=1e-12)
assert not prophet_frame['Prophet_Periodic_Refit'].isna().any()
pd.DataFrame({'Check': ['Rows', 'Timestamp alignment', 'Matches authoritative vector'], 'Pass': [len(prophet_frame) == 1061, pd.DatetimeIndex(prophet_frame['Timestamp']).equals(test.index), np.allclose(validated['Prophet_Periodic_Refit'], prophet_frame['Prophet_Periodic_Refit'], rtol=1e-12, atol=1e-12)]})

                          Check  Pass
0                          Rows  True
1           Timestamp alignment  True
2  Matches authoritative vector  True

## 6. Final Prophet Metrics

In [5]:
prophet_metrics

                                      MAE         RMSE      MAPE     sMAPE
Model
Prophet 30-Day Periodic Refit 8195.262862 10781.162873 11.199767 11.287185