# Cross-Domain Time-Series Forecasting Comparison

Artifact-only comparison of Finance and Energy. Raw MAE/RMSE are never compared numerically across domains.

## 1. Research Objective

Compare model behaviour across Bitcoin and South Australian electricity using within-domain ranks, sMAPE, benchmark-relative changes, trust components, calibration, and protocol-specific significance evidence.

## 2. Domain Summary

In [1]:
from pathlib import Path
import numpy as np,pandas as pd
from IPython.display import display
ROOT=Path.cwd().parent if Path.cwd().name=="notebooks" else Path.cwd();R=ROOT/"results"
domain_summary=pd.DataFrame([{'Domain': 'Bitcoin', 'Field': 'Summary', 'Frequency': 'Daily', 'Target': 'Bitcoin Close price', 'Protocol': 'Rolling one-step', 'Test_Observations': 1061, 'Characteristics': 'Strong persistence; nonstationary price level; high volatility; weak deterministic seasonality'}, {'Domain': 'Electricity', 'Field': 'Protocol A', 'Frequency': '30 minutes', 'Target': 'South Australian demand', 'Protocol': 'Rolling one-step / 30 minutes', 'Test_Observations': 46176, 'Characteristics': 'Persistence; daily and weekly seasonality; recurring demand cycles'}, {'Domain': 'Electricity', 'Field': 'Protocol B', 'Frequency': '30 minutes', 'Target': 'South Australian demand', 'Protocol': '48-step / 24-hour day-ahead', 'Test_Observations': 46176, 'Characteristics': 'Persistence; daily and weekly seasonality; recurring demand cycles'}]);display(domain_summary)

,Domain,Field,Frequency,Target,Protocol,Test_Observations,Characteristics
0,Bitcoin,Summary,Daily,Bitcoin Close price,Rolling one-step,1061,Strong persistence; nonstationary price level;...
1,Electricity,Protocol A,30 minutes,South Australian demand,Rolling one-step / 30 minutes,46176,Persistence; daily and weekly seasonality; rec...
2,Electricity,Protocol B,30 minutes,South Australian demand,48-step / 24-hour day-ahead,46176,Persistence; daily and weekly seasonality; rec...

## 3. Comparable Models

Common families are Naive, the domain-adapted LSTM family, Chronos-Bolt-Tiny, and TimesFM. Bitcoin PE-LSTM and electricity LSTM are not identical architectures or tasks. Seasonal naives, Moving Average, and DHR-ARIMA are electricity-specific benchmarks.

## 4. Accuracy Across Domains

In [2]:
comparison=pd.read_csv(R/"cross_domain_model_comparison.csv");display(comparison.sort_values(["Domain","Protocol","Within_Domain_Rank"]));print("Bitcoin MASE is not invented. Cross-domain interpretation uses sMAPE, within-domain rank, and benchmark-relative changes—not raw MAE/RMSE comparisons.")

,Domain,Protocol,Model,MAE,RMSE,MAPE,sMAPE,Within_Domain_Rank,MASE_48
0,Bitcoin,Rolling one-step daily,Naive,1290.353242,1853.624774,1.742747,1.744142,1,NaN
1,Bitcoin,Rolling one-step daily,Persistence-Enhanced LSTM,1323.040782,1886.566387,1.787392,1.794338,2,NaN
2,Bitcoin,Rolling one-step daily,TimesFM,1349.946786,1924.199337,1.823179,1.823895,3,NaN
3,Bitcoin,Rolling one-step daily,Chronos-Bolt-Tiny,1424.025828,1994.007926,1.934509,1.928782,4,NaN
4,Electricity,Protocol A: rolling one-step 30-minute,TimesFM,16.388292,26.500200,1.349326,1.357575,1,0.140002
5,Electricity,Protocol A: rolling one-step 30-minute,DHR-ARIMA,26.646643,50.289317,2.142715,2.158459,2,0.227636
6,Electricity,Protocol A: rolling one-step 30-minute,Chronos-Bolt-Tiny,32.332012,44.879089,2.643584,2.659078,3,0.276205
7,Electricity,Protocol A: rolling one-step 30-minute,Naive,42.271787,58.272152,3.465892,3.486887,4,0.361118
8,Electricity,Protocol A: rolling one-step 30-minute,LSTM,47.019068,71.565540,3.915375,3.888093,5,0.401673
9,Electricity,Protocol A: rolling one-step 30-minute,Daily Seasonal Naive,129.416180,200.442098,10.640790,10.471882,6,1.105573
10,Electricity,Protocol A: rolling one-step 30-minute,Weekly Seasonal Naive,153.210769,267.161682,11.999432,11.662290,7,1.308845
11,Electricity,Protocol A: rolling one-step 30-minute,Moving Average,179.122226,227.658772,15.243380,14.674740,8,1.530201
12,Electricity,Protocol B: 48-step day-ahead,TimesFM,80.675384,126.984300,6.570199,6.447405,1,0.689192
13,Electricity,Protocol B: 48-step day-ahead,Chronos-Bolt-Tiny,126.119534,188.844105,10.536105,10.099417,2,1.077411
14,Electricity,Protocol B: 48-step day-ahead,Daily Seasonal Naive,129.416180,200.442098,10.640790,10.471882,3,1.105573
15,Electricity,Protocol B: 48-step day-ahead,LSTM,152.926817,210.523254,13.625375,12.313676,4,1.306420
16,Electricity,Protocol B: 48-step day-ahead,Weekly Seasonal Naive,153.210769,267.161682,11.999432,11.662290,5,1.308845
17,Electricity,Protocol B: 48-step day-ahead,Moving Average,203.199277,260.260560,17.756404,16.456455,6,1.735886
18,Electricity,Protocol B: 48-step day-ahead,Naive,243.838179,301.681217,22.907776,19.738307,7,2.083055
19,Electricity,Protocol B: 48-step day-ahead,DHR-ARIMA,287.456183,329.891048,26.429757,22.721487,8,2.455674

Bitcoin MASE is not invented. Cross-domain interpretation uses sMAPE, within-domain rank, and benchmark-relative changes—not raw MAE/RMSE comparisons.

## 5. Baseline Strength Across Domains

In [3]:
relative=pd.DataFrame([{'Domain': 'Bitcoin', 'Protocol': 'Rolling one-step daily', 'Model': 'TimesFM', 'Strongest_Baseline': 'Naive', 'Model_MAE': 1349.9467856090953, 'Baseline_MAE': 1290.3532422243168, 'Relative_MAE_Difference_Percent': 4.618389866797319, 'Model_sMAPE': 1.823894758464343, 'Baseline_sMAPE': 1.7441417265023809, 'Relative_sMAPE_Difference_Percent': 4.572623356812586, 'Beat_Baseline': False}, {'Domain': 'Bitcoin', 'Protocol': 'Rolling one-step daily', 'Model': 'Chronos-Bolt-Tiny', 'Strongest_Baseline': 'Naive', 'Model_MAE': 1424.0258275653864, 'Baseline_MAE': 1290.3532422243168, 'Relative_MAE_Difference_Percent': 10.35937919686583, 'Model_sMAPE': 1.928782487065369, 'Baseline_sMAPE': 1.7441417265023809, 'Relative_sMAPE_Difference_Percent': 10.586339272626537, 'Beat_Baseline': False}, {'Domain': 'Electricity', 'Protocol': 'Protocol A: rolling one-step 30-minute', 'Model': 'TimesFM', 'Strongest_Baseline': 'DHR-ARIMA', 'Model_MAE': 16.38829156817394, 'Baseline_MAE': 26.646643448801345, 'Relative_MAE_Difference_Percent': -38.4977263659407, 'Model_sMAPE': 1.3575753694486183, 'Baseline_sMAPE': 2.158458895937731, 'Relative_sMAPE_Difference_Percent': -37.104414079711866, 'Beat_Baseline': True}, {'Domain': 'Electricity', 'Protocol': 'Protocol A: rolling one-step 30-minute', 'Model': 'Chronos-Bolt-Tiny', 'Strongest_Baseline': 'DHR-ARIMA', 'Model_MAE': 32.33201165869716, 'Baseline_MAE': 26.646643448801345, 'Relative_MAE_Difference_Percent': 21.33615147746334, 'Model_sMAPE': 2.659077985440417, 'Baseline_sMAPE': 2.158458895937731, 'Relative_sMAPE_Difference_Percent': 23.193357559176256, 'Beat_Baseline': False}, {'Domain': 'Electricity', 'Protocol': 'Protocol B: 48-step day-ahead', 'Model': 'TimesFM', 'Strongest_Baseline': 'Daily Seasonal Naive', 'Model_MAE': 80.67538403053535, 'Baseline_MAE': 129.41617978659912, 'Relative_MAE_Difference_Percent': -37.66205727632737, 'Model_sMAPE': 6.447405034935265, 'Baseline_sMAPE': 10.471881770861089, 'Relative_sMAPE_Difference_Percent': -38.4312659747962, 'Beat_Baseline': True}, {'Domain': 'Electricity', 'Protocol': 'Protocol B: 48-step day-ahead', 'Model': 'Chronos-Bolt-Tiny', 'Strongest_Baseline': 'Daily Seasonal Naive', 'Model_MAE': 126.11953364912506, 'Baseline_MAE': 129.41617978659912, 'Relative_MAE_Difference_Percent': -2.547321473180604, 'Model_sMAPE': 10.09941667789778, 'Baseline_sMAPE': 10.471881770861089, 'Relative_sMAPE_Difference_Percent': -3.5568114796685766, 'Beat_Baseline': True}]);display(relative)

,Domain,Protocol,Model,Strongest_Baseline,Model_MAE,Baseline_MAE,Relative_MAE_Difference_Percent,Model_sMAPE,Baseline_sMAPE,Relative_sMAPE_Difference_Percent,Beat_Baseline
0,Bitcoin,Rolling one-step daily,TimesFM,Naive,1349.946786,1290.353242,4.618390,1.823895,1.744142,4.572623,False
1,Bitcoin,Rolling one-step daily,Chronos-Bolt-Tiny,Naive,1424.025828,1290.353242,10.359379,1.928782,1.744142,10.586339,False
2,Electricity,Protocol A: rolling one-step 30-minute,TimesFM,DHR-ARIMA,16.388292,26.646643,-38.497726,1.357575,2.158459,-37.104414,True
3,Electricity,Protocol A: rolling one-step 30-minute,Chronos-Bolt-Tiny,DHR-ARIMA,32.332012,26.646643,21.336151,2.659078,2.158459,23.193358,False
4,Electricity,Protocol B: 48-step day-ahead,TimesFM,Daily Seasonal Naive,80.675384,129.416180,-37.662057,6.447405,10.471882,-38.431266,True
5,Electricity,Protocol B: 48-step day-ahead,Chronos-Bolt-Tiny,Daily Seasonal Naive,126.119534,129.416180,-2.547321,10.099417,10.471882,-3.556811,True

## 6. Foundation Model Performance

In [4]:
foundation=pd.read_csv(R/"cross_domain_foundation_model_comparison.csv");display(foundation)

,Domain,Protocol,Model,Point_Rank,sMAPE,Strongest_Baseline,Relative_MAE_Difference_Percent,Beat_Baseline,Relative_Robustness_Score,Relative_Generalisation_Score,Empirical_80_Coverage,Coverage_Error,Penalised_Trust_Score,Zero_Shot,Inference_Cost
0,Bitcoin,Rolling one-step daily,TimesFM,3,1.823895,Naive,4.618390,False,98.149743,95.992177,0.330820,0.469180,87.510746,True,Recorded in domain notebook; units/protocol di...
1,Bitcoin,Rolling one-step daily,Chronos-Bolt-Tiny,4,1.928782,Naive,10.359379,False,95.434840,93.750212,0.845429,0.045429,90.577907,True,Recorded in domain notebook; units/protocol di...
2,Electricity,Protocol A: rolling one-step 30-minute,TimesFM,1,1.357575,DHR-ARIMA,-38.497726,True,100.000000,100.000000,0.336495,0.463505,92.033197,True,Recorded in domain notebook; units/protocol di...
3,Electricity,Protocol A: rolling one-step 30-minute,Chronos-Bolt-Tiny,3,2.659078,DHR-ARIMA,21.336151,False,33.528650,52.022174,0.911231,0.111231,51.043105,True,Recorded in domain notebook; units/protocol di...
4,Electricity,Protocol B: 48-step day-ahead,TimesFM,1,6.447405,Daily Seasonal Naive,-37.662057,True,100.000000,100.000000,0.245604,0.554396,91.078842,True,Recorded in domain notebook; units/protocol di...
5,Electricity,Protocol B: 48-step day-ahead,Chronos-Bolt-Tiny,2,10.099417,Daily Seasonal Naive,-2.547321,True,73.004135,63.114964,0.676239,0.123761,66.311491,True,Recorded in domain notebook; units/protocol di...

## 7. Robustness Across Domains

In [5]:
trust=pd.DataFrame([{'Domain': 'Bitcoin', 'Protocol': 'Rolling one-step daily', 'Model': 'Naive', 'Relative Accuracy Score': 100.0, 'Relative Robustness Score': 100.0, 'Relative Generalisation Score': 100.0, 'Uncertainty Score': 82.31626, 'Explainability Score': 99.0, 'Penalised Trust Score': 97.247439, 'Evidence-Available Trust Score': 97.247439, 'Component_Basis': 'Bitcoin frozen RMSE-relative framework'}, {'Domain': 'Bitcoin', 'Protocol': 'Rolling one-step daily', 'Model': 'Persistence-Enhanced LSTM', 'Relative Accuracy Score': 98.253885, 'Relative Robustness Score': 98.545144, 'Relative Generalisation Score': 98.173252, 'Uncertainty Score': None, 'Explainability Score': 57.0, 'Penalised Trust Score': 79.432539, 'Evidence-Available Trust Score': 93.450046, 'Component_Basis': 'Bitcoin frozen RMSE-relative framework'}, {'Domain': 'Bitcoin', 'Protocol': 'Rolling one-step daily', 'Model': 'Chronos-Bolt-Tiny', 'Relative Accuracy Score': 92.95975, 'Relative Robustness Score': 95.43484, 'Relative Generalisation Score': 93.750212, 'Uncertainty Score': 88.699897, 'Explainability Score': 69.0, 'Penalised Trust Score': 90.577907, 'Evidence-Available Trust Score': 90.577907, 'Component_Basis': 'Bitcoin frozen RMSE-relative framework'}, {'Domain': 'Bitcoin', 'Protocol': 'Rolling one-step daily', 'Model': 'TimesFM', 'Relative Accuracy Score': 96.332263, 'Relative Robustness Score': 98.149743, 'Relative Generalisation Score': 95.992177, 'Uncertainty Score': 57.7738, 'Explainability Score': 63.0, 'Penalised Trust Score': 87.510746, 'Evidence-Available Trust Score': 87.510746, 'Component_Basis': 'Bitcoin frozen RMSE-relative framework'}, {'Domain': 'Electricity', 'Protocol': 'Protocol A: rolling one-step 30-minute', 'Model': 'TimesFM', 'Relative Accuracy Score': 100.0, 'Relative Robustness Score': 100.0, 'Relative Generalisation Score': 100.0, 'Uncertainty Score': 67.55465, 'Explainability Score': 69.0, 'Penalised Trust Score': 92.0331975, 'Evidence-Available Trust Score': 92.0331975, 'Component_Basis': 'Electricity frozen MASE-48-relative framework'}, {'Domain': 'Electricity', 'Protocol': 'Protocol A: rolling one-step 30-minute', 'Model': 'DHR-ARIMA', 'Relative Accuracy Score': 61.5022736341, 'Relative Robustness Score': 59.2372598277, 'Relative Generalisation Score': 61.2757233144, 'Uncertainty Score': None, 'Explainability Score': 79.0, 'Penalised Trust Score': 53.5283924003, 'Evidence-Available Trust Score': 62.9745792945, 'Component_Basis': 'Electricity frozen MASE-48-relative framework'}, {'Domain': 'Electricity', 'Protocol': 'Protocol A: rolling one-step 30-minute', 'Model': 'Chronos-Bolt-Tiny', 'Relative Accuracy Score': 50.6875097695, 'Relative Robustness Score': 33.5286504411, 'Relative Generalisation Score': 52.0221742948, 'Uncertainty Score': 65.9487419153, 'Explainability Score': 63.0, 'Penalised Trust Score': 51.0431046538, 'Evidence-Available Trust Score': 51.0431046538, 'Component_Basis': 'Electricity frozen MASE-48-relative framework'}, {'Domain': 'Electricity', 'Protocol': 'Protocol A: rolling one-step 30-minute', 'Model': 'Naive', 'Relative Accuracy Score': 38.768863474, 'Relative Robustness Score': 36.9660857643, 'Relative Generalisation Score': 38.6878453236, 'Uncertainty Score': None, 'Explainability Score': 99.0, 'Penalised Trust Score': 38.5998884335, 'Evidence-Available Trust Score': 45.4116334511, 'Component_Basis': 'Electricity frozen MASE-48-relative framework'}, {'Domain': 'Electricity', 'Protocol': 'Protocol A: rolling one-step 30-minute', 'Model': 'LSTM', 'Relative Accuracy Score': 34.8545647924, 'Relative Robustness Score': 36.1889310666, 'Relative Generalisation Score': 35.2841615235, 'Uncertainty Score': None, 'Explainability Score': 57.0, 'Penalised Trust Score': 32.1937161953, 'Evidence-Available Trust Score': 37.8749602298, 'Component_Basis': 'Electricity frozen MASE-48-relative framework'}, {'Domain': 'Electricity', 'Protocol': 'Protocol A: rolling one-step 30-minute', 'Model': 'Daily Seasonal Naive', 'Relative Accuracy Score': 12.663247822, 'Relative Robustness Score': 6.8976162031, 'Relative Generalisation Score': 12.4889368992, 'Uncertainty Score': None, 'Explainability Score': 99.0, 'Penalised Trust Score': 18.2094473582, 'Evidence-Available Trust Score': 21.4228792449, 'Component_Basis': 'Electricity frozen MASE-48-relative framework'}, {'Domain': 'Electricity', 'Protocol': 'Protocol A: rolling one-step 30-minute', 'Model': 'Weekly Seasonal Naive', 'Relative Accuracy Score': 10.6965663701, 'Relative Robustness Score': 2.4843115398, 'Relative Generalisation Score': 9.8457743827, 'Uncertainty Score': None, 'Explainability Score': 99.0, 'Penalised Trust Score': 16.109815414, 'Evidence-Available Trust Score': 18.9527240165, 'Component_Basis': 'Electricity frozen MASE-48-relative framework'}, {'Domain': 'Electricity', 'Protocol': 'Protocol A: rolling one-step 30-minute', 'Model': 'Moving Average', 'Relative Accuracy Score': 9.1492228206, 'Relative Robustness Score': 4.0978419224, 'Relative Generalisation Score': 9.3889345954, 'Uncertainty Score': None, 'Explainability Score': 96.0, 'Penalised Trust Score': 15.4995832908, 'Evidence-Available Trust Score': 18.2348038715, 'Component_Basis': 'Electricity frozen MASE-48-relative framework'}, {'Domain': 'Electricity', 'Protocol': 'Protocol B: 48-step day-ahead', 'Model': 'TimesFM', 'Relative Accuracy Score': 100.0, 'Relative Robustness Score': 100.0, 'Relative Generalisation Score': 100.0, 'Uncertainty Score': 61.19228, 'Explainability Score': 69.0, 'Penalised Trust Score': 91.078842, 'Evidence-Available Trust Score': 91.078842, 'Component_Basis': 'Electricity frozen MASE-48-relative framework'}, {'Domain': 'Electricity', 'Protocol': 'Protocol B: 48-step day-ahead', 'Model': 'Chronos-Bolt-Tiny', 'Relative Accuracy Score': 63.9673979885, 'Relative Robustness Score': 73.00413541, 'Relative Generalisation Score': 63.1149641782, 'Uncertainty Score': 69.3272142784, 'Explainability Score': 63.0, 'Penalised Trust Score': 66.3114913554, 'Evidence-Available Trust Score': 66.3114913554, 'Component_Basis': 'Electricity frozen MASE-48-relative framework'}, {'Domain': 'Electricity', 'Protocol': 'Protocol B: 48-step day-ahead', 'Model': 'Daily Seasonal Naive', 'Relative Accuracy Score': 62.3379427237, 'Relative Robustness Score': 76.1653536675, 'Relative Generalisation Score': 60.6499384527, 'Uncertainty Score': None, 'Explainability Score': 99.0, 'Penalised Trust Score': 59.0813383773, 'Evidence-Available Trust Score': 69.5074569145, 'Component_Basis': 'Electricity frozen MASE-48-relative framework'}, {'Domain': 'Electricity', 'Protocol': 'Protocol B: 48-step day-ahead', 'Model': 'LSTM', 'Relative Accuracy Score': 52.7542427014, 'Relative Robustness Score': 67.8416010942, 'Relative Generalisation Score': 51.567653663, 'Uncertainty Score': None, 'Explainability Score': 57.0, 'Penalised Trust Score': 48.0458358969, 'Evidence-Available Trust Score': 56.5245128199, 'Component_Basis': 'Electricity frozen MASE-48-relative framework'}, {'Domain': 'Electricity', 'Protocol': 'Protocol B: 48-step day-ahead', 'Model': 'Weekly Seasonal Naive', 'Relative Accuracy Score': 52.6564710009, 'Relative Robustness Score': 33.5865887734, 'Relative Generalisation Score': 47.8139664847, 'Uncertainty Score': None, 'Explainability Score': 99.0, 'Penalised Trust Score': 44.6098759019, 'Evidence-Available Trust Score': 52.4822069434, 'Component_Basis': 'Electricity frozen MASE-48-relative framework'}, {'Domain': 'Electricity', 'Protocol': 'Protocol B: 48-step day-ahead', 'Model': 'Moving Average', 'Relative Accuracy Score': 39.702594064, 'Relative Robustness Score': 49.9435122955, 'Relative Generalisation Score': 39.6150465508, 'Uncertainty Score': None, 'Explainability Score': 96.0, 'Penalised Trust Score': 41.4076196917, 'Evidence-Available Trust Score': 48.7148466961, 'Component_Basis': 'Electricity frozen MASE-48-relative framework'}, {'Domain': 'Electricity', 'Protocol': 'Protocol B: 48-step day-ahead', 'Model': 'Naive', 'Relative Accuracy Score': 33.0856243954, 'Relative Robustness Score': 46.1735825696, 'Relative Generalisation Score': 32.5958379191, 'Uncertainty Score': None, 'Explainability Score': 99.0, 'Penalised Trust Score': 37.2338526361, 'Evidence-Available Trust Score': 43.8045325131, 'Component_Basis': 'Electricity frozen MASE-48-relative framework'}, {'Domain': 'Electricity', 'Protocol': 'Protocol B: 48-step day-ahead', 'Model': 'DHR-ARIMA', 'Relative Accuracy Score': 28.0652805207, 'Relative Robustness Score': 45.8631821846, 'Relative Generalisation Score': 27.0327321737, 'Uncertainty Score': None, 'Explainability Score': 79.0, 'Penalised Trust Score': 32.3020310539, 'Evidence-Available Trust Score': 38.0023894752, 'Component_Basis': 'Electricity frozen MASE-48-relative framework'}]);display(trust[trust.Model.isin(["Naive","Persistence-Enhanced LSTM","LSTM","Chronos-Bolt-Tiny","TimesFM"])][["Domain","Protocol","Model","Relative Robustness Score"]])

,Domain,Protocol,Model,Relative Robustness Score
0,Bitcoin,Rolling one-step daily,Naive,100.000000
1,Bitcoin,Rolling one-step daily,Persistence-Enhanced LSTM,98.545144
2,Bitcoin,Rolling one-step daily,Chronos-Bolt-Tiny,95.434840
3,Bitcoin,Rolling one-step daily,TimesFM,98.149743
4,Electricity,Protocol A: rolling one-step 30-minute,TimesFM,100.000000
6,Electricity,Protocol A: rolling one-step 30-minute,Chronos-Bolt-Tiny,33.528650
7,Electricity,Protocol A: rolling one-step 30-minute,Naive,36.966086
8,Electricity,Protocol A: rolling one-step 30-minute,LSTM,36.188931
12,Electricity,Protocol B: 48-step day-ahead,TimesFM,100.000000
13,Electricity,Protocol B: 48-step day-ahead,Chronos-Bolt-Tiny,73.004135
15,Electricity,Protocol B: 48-step day-ahead,LSTM,67.841601
18,Electricity,Protocol B: 48-step day-ahead,Naive,46.173583

## 8. Generalisation Across Domains

In [6]:
display(trust[trust.Model.isin(["Naive","Persistence-Enhanced LSTM","LSTM","Chronos-Bolt-Tiny","TimesFM"])][["Domain","Protocol","Model","Relative Generalisation Score"]])

,Domain,Protocol,Model,Relative Generalisation Score
0,Bitcoin,Rolling one-step daily,Naive,100.000000
1,Bitcoin,Rolling one-step daily,Persistence-Enhanced LSTM,98.173252
2,Bitcoin,Rolling one-step daily,Chronos-Bolt-Tiny,93.750212
3,Bitcoin,Rolling one-step daily,TimesFM,95.992177
4,Electricity,Protocol A: rolling one-step 30-minute,TimesFM,100.000000
6,Electricity,Protocol A: rolling one-step 30-minute,Chronos-Bolt-Tiny,52.022174
7,Electricity,Protocol A: rolling one-step 30-minute,Naive,38.687845
8,Electricity,Protocol A: rolling one-step 30-minute,LSTM,35.284162
12,Electricity,Protocol B: 48-step day-ahead,TimesFM,100.000000
13,Electricity,Protocol B: 48-step day-ahead,Chronos-Bolt-Tiny,63.114964
15,Electricity,Protocol B: 48-step day-ahead,LSTM,51.567654
18,Electricity,Protocol B: 48-step day-ahead,Naive,32.595838

## 9. Uncertainty Calibration Across Domains

In [7]:
uncertainty=pd.read_csv(R/"cross_domain_uncertainty_comparison.csv");display(uncertainty);print("Interval widths retain domain-specific units and are not compared numerically across domains.")

,Domain,Protocol,Model,Nominal_Coverage,Empirical_Coverage,Coverage_Error,Average_Width,Width_Units
0,Bitcoin,Rolling one-step daily,Chronos-Bolt-Tiny,0.8,0.845429,0.045429,5151.959961,Bitcoin price units
1,Bitcoin,Rolling one-step daily,TimesFM,0.8,0.330820,0.469180,1436.627452,Bitcoin price units
2,Electricity,Protocol A: rolling one-step 30-minute,Chronos-Bolt-Tiny,0.8,0.911231,0.111231,137.419281,Electricity demand units
3,Electricity,Protocol A: rolling one-step 30-minute,TimesFM,0.8,0.336495,0.463505,17.108297,Electricity demand units
4,Electricity,Protocol B: 48-step day-ahead,Chronos-Bolt-Tiny,0.8,0.676239,0.123761,283.997589,Electricity demand units
5,Electricity,Protocol B: 48-step day-ahead,TimesFM,0.8,0.245604,0.554396,75.642609,Electricity demand units

Interval widths retain domain-specific units and are not compared numerically across domains.

## 10. Statistical Significance Across Domains

In [8]:
significance=pd.read_csv(R/"cross_domain_significance_summary.csv");display(significance);print("No p-values are pooled across domains.")

,Domain,Protocol,Comparison,Lower_Loss_Model,p_value,P_Value_Type,Significant,Practical_Interpretation
0,Bitcoin,Rolling one-step daily,Naive vs TimesFM,Naive,2.100000e-05,Raw,True,TimesFM does not beat persistence; Naive has l...
1,Bitcoin,Rolling one-step daily,Naive vs Chronos-Bolt-Tiny,Naive,0.000000e+00,Raw,True,Naive has lower squared loss.
2,Bitcoin,Rolling one-step daily,TimesFM vs Chronos-Bolt-Tiny,TimesFM,5.862000e-03,Raw,True,TimesFM improves on Chronos but not Naive.
3,Bitcoin,Rolling one-step daily,Persistence-Enhanced LSTM vs TimesFM,Persistence-Enhanced LSTM,1.234950e-01,Raw,False,No statistically significant difference was de...
4,Electricity,Protocol A: rolling one-step 30-minute,TimesFM vs DHR ARIMA,TimesFM,0.000000e+00,Benjamini-Hochberg adjusted,True,TimesFM significantly beats the strongest one-...
5,Electricity,Protocol A: rolling one-step 30-minute,TimesFM vs Chronos Bolt Tiny,TimesFM,1.731906e-207,Benjamini-Hochberg adjusted,True,TimesFM significantly beats Chronos.
6,Electricity,Protocol A: rolling one-step 30-minute,Chronos Bolt Tiny vs Naive,Chronos Bolt Tiny,1.021519e-151,Benjamini-Hochberg adjusted,True,Chronos significantly beats Naive on squared l...
7,Electricity,Protocol B: 48-step day-ahead,TimesFM vs Chronos Bolt Tiny,TimesFM,4.563702e-18,Benjamini-Hochberg adjusted,True,TimesFM significantly beats Chronos.
8,Electricity,Protocol B: 48-step day-ahead,TimesFM vs Daily Seasonal Naive,TimesFM,2.318985e-26,Benjamini-Hochberg adjusted,True,TimesFM significantly beats the strongest day-...
9,Electricity,Protocol B: 48-step day-ahead,Chronos Bolt Tiny vs Daily Seasonal Naive,Chronos Bolt Tiny,2.231343e-03,Benjamini-Hochberg adjusted,True,Chronos has significantly lower daily squared ...

No p-values are pooled across domains.

## 11. Trustworthiness Across Domains

In [9]:
display(trust[trust.Model.isin(["Naive","Persistence-Enhanced LSTM","LSTM","Chronos-Bolt-Tiny","TimesFM"])])

,Domain,Protocol,Model,Relative Accuracy Score,Relative Robustness Score,Relative Generalisation Score,Uncertainty Score,Explainability Score,Penalised Trust Score,Evidence-Available Trust Score,Component_Basis
0,Bitcoin,Rolling one-step daily,Naive,100.000000,100.000000,100.000000,82.316260,99.0,97.247439,97.247439,Bitcoin frozen RMSE-relative framework
1,Bitcoin,Rolling one-step daily,Persistence-Enhanced LSTM,98.253885,98.545144,98.173252,NaN,57.0,79.432539,93.450046,Bitcoin frozen RMSE-relative framework
2,Bitcoin,Rolling one-step daily,Chronos-Bolt-Tiny,92.959750,95.434840,93.750212,88.699897,69.0,90.577907,90.577907,Bitcoin frozen RMSE-relative framework
3,Bitcoin,Rolling one-step daily,TimesFM,96.332263,98.149743,95.992177,57.773800,63.0,87.510746,87.510746,Bitcoin frozen RMSE-relative framework
4,Electricity,Protocol A: rolling one-step 30-minute,TimesFM,100.000000,100.000000,100.000000,67.554650,69.0,92.033197,92.033197,Electricity frozen MASE-48-relative framework
6,Electricity,Protocol A: rolling one-step 30-minute,Chronos-Bolt-Tiny,50.687510,33.528650,52.022174,65.948742,63.0,51.043105,51.043105,Electricity frozen MASE-48-relative framework
7,Electricity,Protocol A: rolling one-step 30-minute,Naive,38.768863,36.966086,38.687845,NaN,99.0,38.599888,45.411633,Electricity frozen MASE-48-relative framework
8,Electricity,Protocol A: rolling one-step 30-minute,LSTM,34.854565,36.188931,35.284162,NaN,57.0,32.193716,37.874960,Electricity frozen MASE-48-relative framework
12,Electricity,Protocol B: 48-step day-ahead,TimesFM,100.000000,100.000000,100.000000,61.192280,69.0,91.078842,91.078842,Electricity frozen MASE-48-relative framework
13,Electricity,Protocol B: 48-step day-ahead,Chronos-Bolt-Tiny,63.967398,73.004135,63.114964,69.327214,63.0,66.311491,66.311491,Electricity frozen MASE-48-relative framework
15,Electricity,Protocol B: 48-step day-ahead,LSTM,52.754243,67.841601,51.567654,NaN,57.0,48.045836,56.524513,Electricity frozen MASE-48-relative framework
18,Electricity,Protocol B: 48-step day-ahead,Naive,33.085624,46.173583,32.595838,NaN,99.0,37.233853,43.804533,Electricity frozen MASE-48-relative framework

## 12. Forecast-Horizon Effects

Bitcoin is daily one-step; Electricity A is 30-minute one-step; Electricity B is true 48-step day-ahead. Naive and DHR-ARIMA are strongest at short horizons, while Daily Seasonal Naive becomes competitive day-ahead. TimesFM remains strong under both electricity horizons. Domain and horizon effects cannot be disentangled completely.

## 13. Cross-Domain Model Ranking

In [10]:
rank_stability=pd.DataFrame([{'Model': 'Naive', 'Bitcoin_Rank': 1, 'Electricity_Protocol_A_Rank': 4, 'Electricity_Protocol_B_Rank': 7, 'Mean_Rank': 4.0, 'Rank_Std': 2.449489742783178, 'Best_Rank': 1, 'Worst_Rank': 7}, {'Model': 'LSTM family', 'Bitcoin_Rank': 2, 'Electricity_Protocol_A_Rank': 5, 'Electricity_Protocol_B_Rank': 4, 'Mean_Rank': 3.6666666666666665, 'Rank_Std': 1.247219128924647, 'Best_Rank': 2, 'Worst_Rank': 5}, {'Model': 'Chronos-Bolt-Tiny', 'Bitcoin_Rank': 4, 'Electricity_Protocol_A_Rank': 3, 'Electricity_Protocol_B_Rank': 2, 'Mean_Rank': 3.0, 'Rank_Std': 0.816496580927726, 'Best_Rank': 2, 'Worst_Rank': 4}, {'Model': 'TimesFM', 'Bitcoin_Rank': 3, 'Electricity_Protocol_A_Rank': 1, 'Electricity_Protocol_B_Rank': 1, 'Mean_Rank': 1.6666666666666667, 'Rank_Std': 0.9428090415820634, 'Best_Rank': 1, 'Worst_Rank': 3}]);display(rank_stability);print("Rank sets differ: Bitcoin has four authoritative common models; electricity rankings include eight models.")

,Model,Bitcoin_Rank,Electricity_Protocol_A_Rank,Electricity_Protocol_B_Rank,Mean_Rank,Rank_Std,Best_Rank,Worst_Rank
0,Naive,1,4,7,4.000000,2.449490,1,7
1,LSTM family,2,5,4,3.666667,1.247219,2,5
2,Chronos-Bolt-Tiny,4,3,2,3.000000,0.816497,2,4
3,TimesFM,3,1,1,1.666667,0.942809,1,3

Rank sets differ: Bitcoin has four authoritative common models; electricity rankings include eight models.

## 14. Research Findings

In [11]:
print("RQ1: Foundation models are not consistently dominant: both trail persistence in Bitcoin, while TimesFM leads both electricity protocols.")
print("RQ2: Yes. Persistence dominates Bitcoin; TimesFM dominates structured electricity demand.")
print("RQ3: No. TimesFM beats both electricity benchmarks but not Bitcoin Naive.")
print("RQ4: Chronos is consistently closer to nominal coverage; TimesFM consistently undercovers.")
print("RQ5: No. Simple baselines can be more trustworthy than complex models.")
print("RQ6: Horizon materially changes ranks: DHR-ARIMA falls and Daily Seasonal Naive rises in day-ahead electricity.")

RQ1: Foundation models are not consistently dominant: both trail persistence in Bitcoin, while TimesFM leads both electricity protocols.
RQ2: Yes. Persistence dominates Bitcoin; TimesFM dominates structured electricity demand.
RQ3: No. TimesFM beats both electricity benchmarks but not Bitcoin Naive.
RQ4: Chronos is consistently closer to nominal coverage; TimesFM consistently undercovers.
RQ5: No. Simple baselines can be more trustworthy than complex models.
RQ6: Horizon materially changes ranks: DHR-ARIMA falls and Daily Seasonal Naive rises in day-ahead electricity.

## 15. Limitations

Only two domains are complete; frequencies and horizons differ; LSTM formulations are domain-adapted; Chronos and TimesFM architectures/model sizes differ; quantiles are limited; Trust weights are researcher-defined; only South Australia is evaluated; no Moirai/PatchTST/iTransformer results exist; conclusions remain preliminary until Weather and Transport are added.

## 16. Validation Checks

In [12]:
audit=pd.DataFrame([{'Check': 'artifact-only analysis', 'Pass/Fail': 'PASS', 'Evidence': 'True'}, {'Check': 'no model loading', 'Pass/Fail': 'PASS', 'Evidence': 'True'}, {'Check': 'no model fitting', 'Pass/Fail': 'PASS', 'Evidence': 'True'}, {'Check': 'no forecast regeneration', 'Pass/Fail': 'PASS', 'Evidence': 'True'}, {'Check': 'Bitcoin artifacts unchanged', 'Pass/Fail': 'PASS', 'Evidence': 'True'}, {'Check': 'Electricity artifacts unchanged', 'Pass/Fail': 'PASS', 'Evidence': 'True'}, {'Check': 'no raw MAE comparison across incompatible domains', 'Pass/Fail': 'PASS', 'Evidence': 'True'}, {'Check': 'Protocol A/B remain distinct', 'Pass/Fail': 'PASS', 'Evidence': 'True'}, {'Check': 'no cross-domain p-value pooling', 'Pass/Fail': 'PASS', 'Evidence': 'True'}, {'Check': 'relative baseline calculations correct', 'Pass/Fail': 'PASS', 'Evidence': 'True'}, {'Check': 'uncertainty values trace to saved evidence', 'Pass/Fail': 'PASS', 'Evidence': 'True'}, {'Check': 'model ranks reproduce domain analyses', 'Pass/Fail': 'PASS', 'Evidence': 'True'}, {'Check': 'no unsupported claims', 'Pass/Fail': 'PASS', 'Evidence': 'True'}]);display(audit);assert audit["Pass/Fail"].eq("PASS").all()

                                                Check Pass/Fail Evidence
0                              artifact-only analysis      PASS     True
1                                    no model loading      PASS     True
2                                    no model fitting      PASS     True
3                            no forecast regeneration      PASS     True
4                         Bitcoin artifacts unchanged      PASS     True
5                     Electricity artifacts unchanged      PASS     True
6   no raw MAE comparison across incompatible domains      PASS     True
7                        Protocol A/B remain distinct      PASS     True
8                     no cross-domain p-value pooling      PASS     True
9              relative baseline calculations correct      PASS     True
10         uncertainty values trace to saved evidence      PASS     True
11              model ranks reproduce domain analyses      PASS     True
12                              no unsupported claims      PASS     True